# .github/workflows/deploy.yml
name: Build and deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main    # ← change to 'master' if that’s your default branch

# Grant minimal permissions needed for Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Use the built-in 'github-pages' environment for branch protection metadata
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-pages.outputs.page_url }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Pre-build (npm)
        run: pacman -S --noconfirm nodejs npm

      - name: Build site
        run: bundle exec jekyll build --destination _site

      - name: Configure Pages
        uses: actions/configure-pages@v5  # ensures Pages is enabled & records metadata :contentReference[oaicite:0]{index=0}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3  # v3 is required for compatibility :contentReference[oaicite:1]{index=1}
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deploy-to-pages
        uses: actions/deploy-pages@v4         # requires upload-pages-artifact@v3 :contentReference[oaicite:2]{index=2}
